apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: cargo-containers-db-container
  name: cargo-containers-db-container
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cargo-containers-db-container
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: cargo-containers-db-container
    spec:
      containers:
      - args:
        - -p
        - "5438"
        env:
        - name: POSTGRES_DB
          value: cargo_containers_db
        - name: POSTGRES_PASSWORD
          value: root
        - name: POSTGRES_USER
          value: postgres
        image: postgres
        imagePullPolicy: ""
        name: cargo-containers-db-container
        ports:
        - containerPort: 5438
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
