version: '3.1'
services:
  app:
    container_name: cargo-container-ms
    image: durpyshark/cargo-container-ms
    build: ./
    ports:
      - "8086:8086"
    depends_on:
      - cargo_containers_db_container
  cargo_containers_db_container:
    image: postgres
    ports:
      - "5438:5438"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cargo_containers_db
    command: -p 5438